### PR TITLE
Set up commitlint 

### PR DESCRIPTION
**Pull request by taylorn16**

### CODE REVIEW

**Comment by taylorn16** [comment]
Ok @rmjohnson this should be g2g. This sets up linting commits according to [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) both locally using husky's commit-msg hook and also on the CI build

**Review by rmjohnson-olo — APPROVED** [review]
🎊

EDIT: whoops, wrong account 😅

**Comment by taylorn16** [comment]
> 🎊
> 
> EDIT: whoops, wrong account 😅

😆

**Comment by taylorn16** [comment]
@rmjohnson I went rogue and merged since you _technically_ approved 😂

**Pull request merged**
