### PR TITLE
add es modules exports

### PR DESCRIPTION
**Pull request by taylorn16**

### CODE REVIEW

**Comment by taylorn16** [comment]
@rmjohnson you should be able to peep the generated docs site locally if you pull down this branch and do `npm i` then `npx typedoc --entryPointStrategy expand ./src`. It generates the site in the `docs/` directory.

It turns out that for `@example` code blocks to be rendered, they have to be wrapped in triple-backticks, but only if they contain a backtick character in the example 🤷‍♂️

**Comment by rmjohnson** [comment]
@taylorn16, just ran this locally and got several warnings. Are you looking at those or would it help if I did?

**Comment by taylorn16** [comment]
> @taylorn16, just ran this locally and got several warnings. Are you looking at those or would it help if I did?

Yeah if you could that would be helpful. I ignored those for the time being (most of them looked like things I had intentionally `@ignore`d because they were internal details). I was mostly concerned with getting the actual website looking ship-shape 😮‍💨

**Review by rmjohnson — DISMISSED** [review]
In that case let's ship this thing!

**Comment by taylorn16** [comment]
> In that case let's ship this thing!

Should I open a separate issue to address the warnings?

**Comment by rmjohnson** [comment]
> Should I open a separate issue to address the warnings?

Sounds good to me :+1: I can take a look at those after we merge.

**Comment by taylorn16** [comment]
ok @rmjohnson should be good for re-approve

**Comment by taylorn16** [comment]
I'm seeing some _wonky_ test coverage numbers. It's saying only 56% of functions are covered in the Result file or something absurd, even though it only shows 3 uncovered lines in the whole file 🤷

**Review by rmjohnson — APPROVED** [review]

**Pull request merged**
