### PR TITLE
Write the readme

### PR DESCRIPTION
**Pull request by taylorn16**

### CODE REVIEW

**Comment by taylorn16** [comment]
@rmjohnson still a bunch of TODOs left but the stuff that is in there should be ready for review

**Review by rmjohnson — DISMISSED** [review]
Great job @taylorn16 ! :clap:

**Comment by taylorn16** [comment]
Alright @rmjohnson this should be good for final review now

**Comment by taylorn16** [comment]
@rmjohnson going rogue so I can move forward with package publishing stuff

**Pull request merged**
